#!/bin/bash
AFLAGS="-f elf"
CFLAGS="-m32 -g -fno-rtti -fno-exceptions -fno-stack-protector"
LFLAGS="-melf_i386"

nasm $AFLAGS -o entry.o entry.asm
nasm $AFLAGS -o descript_cpu.o descript_cpu.asm

gcc $CFLAGS -c descript.cpp -o descript.o
gcc $CFLAGS -c runtime.cpp -o runtime.o
gcc $CFLAGS -c main.cpp -o main.o
gcc $CFLAGS -c debug.cpp -o debug.o
gcc $CFLAGS -c tools.cpp -o tools.o
gcc $CFLAGS -c mem_physical.cpp -o mem_physical.o
gcc $CFLAGS -c mem_logical.cpp -o mem_logical.o

ld $LFLAGS -T Kernel.ld -Map kernel.map -o kernel.elf entry.o main.o debug.o tools.o runtime.o descript.o descript_cpu.o mem_logical.o mem_physical.o
